version: '3'
services:
  moives:
    image: naidukiran/moives:latest
    ports: 
      - "80:80"
    deploy:
      replicas: 3
  
  train:
    image: naidukiran/train:latest
    ports: 
      - "81:80"
    deploy:
      replicas: 3
  
  paytm:
    image: naidukiran/paytm:latest
    ports: 
      - "82:80"
    deploy:
      replicas: 3

